package vista;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JButton;
import controlador.controladorDashboard;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Horo
 */
public class vistaDashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public vistaDashboard() {
        initComponents();
        setLocationRelativeTo(null);  
        URL url = getClass().getResource("/imagenes/logoCarisma.jpg");
        ImageIcon img = new ImageIcon(url);
        setIconImage(img.getImage());    
        innerBodyPanel.setVisible(false);
        inventarioSubMenuPanel.setVisible(false);
        ventasSubMenuPanel.setVisible(false);
        reportesSubMenuPanel.setVisible(false);
        opcionesSubMenuPanel.setVisible(false);
    }
    private void close(){
        try {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            this.addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent e){
                    confirmarSalida();         
                }
            });
            this.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }  
    public void confirmarSalida(){
        int valor = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea salir del sistema?","Advertencia", 
                                                 JOptionPane.YES_NO_OPTION);
        if (valor == JOptionPane.YES_OPTION){
            System.exit(0);
            
        }
    }
    public void despliegaPantalla(){
        setLocationRelativeTo(null);
        setVisible(true);
    }
     public void setControladorDashboard (controladorDashboard objControladorDashboard){

        categoriasBTN.addActionListener(objControladorDashboard);
        productosBTN.addActionListener(objControladorDashboard);
        detalleVentasBTN.addActionListener(objControladorDashboard);
        ventasRealizadasBTN.addActionListener(objControladorDashboard);
        stockProductosBTN.addActionListener(objControladorDashboard);
        configurarUsuarioBTN.addActionListener(objControladorDashboard);
        
        categoriasBTN.setActionCommand(controladorDashboard.botonCategorias);
        productosBTN.setActionCommand(controladorDashboard.botonProductos);
        detalleVentasBTN.setActionCommand(controladorDashboard.botonDetalleVenta);
        ventasRealizadasBTN.setActionCommand(controladorDashboard.botonVentasRealizadas);
        stockProductosBTN.setActionCommand(controladorDashboard.botonStockProductos);
        configurarUsuarioBTN.setActionCommand(controladorDashboard.botonConfigurarUsuario);
        
    }
        public void cerrarMenu(){
        innerBodyPanel.setVisible(false);
        inventarioSubMenuPanel.setVisible(false);
        ventasSubMenuPanel.setVisible(false);
        reportesSubMenuPanel.setVisible(false);
        opcionesSubMenuPanel.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        versionLBL = new javax.swing.JLabel();
        brandLBL = new javax.swing.JLabel();
        logoLBL = new javax.swing.JLabel();
        btnPanel = new javax.swing.JPanel();
        inventarioBTN = new javax.swing.JButton();
        ventasBTN = new javax.swing.JButton();
        opcionesBTN = new javax.swing.JButton();
        reportesBTN = new javax.swing.JButton();
        brandLBL2 = new javax.swing.JLabel();
        copyrightLBL = new javax.swing.JLabel();
        innerBodyPanel = new javax.swing.JPanel();
        opcionesSubMenuPanel = new javax.swing.JPanel();
        configurarUsuarioBTN = new javax.swing.JButton();
        inventarioSubMenuPanel = new javax.swing.JPanel();
        productosBTN = new javax.swing.JButton();
        categoriasBTN = new javax.swing.JButton();
        ventasSubMenuPanel = new javax.swing.JPanel();
        detalleVentasBTN = new javax.swing.JButton();
        reportesSubMenuPanel = new javax.swing.JPanel();
        ventasRealizadasBTN = new javax.swing.JButton();
        stockProductosBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(670, 520));
        setMinimumSize(new java.awt.Dimension(670, 520));
        setPreferredSize(new java.awt.Dimension(670, 520));
        setResizable(false);

        bodyPanel.setBackground(java.awt.Color.white);
        bodyPanel.setPreferredSize(new java.awt.Dimension(1080, 720));
        bodyPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bodyPanelMouseClicked(evt);
            }
        });

        headerPanel.setBackground(new java.awt.Color(237, 239, 245));

        versionLBL.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        versionLBL.setText("v 1.1");

        brandLBL.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        brandLBL.setText("Punto De Venta");

        logoLBL.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        logoLBL.setForeground(new java.awt.Color(255, 255, 255));
        logoLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/shop 64x64.png"))); // NOI18N

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(logoLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(brandLBL)
                    .addComponent(versionLBL))
                .addContainerGap(290, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoLBL)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addComponent(brandLBL)
                        .addGap(4, 4, 4)
                        .addComponent(versionLBL)
                        .addGap(7, 7, 7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPanel.setBackground(new java.awt.Color(242, 173, 132));
        btnPanel.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));

        inventarioBTN.setBackground(new java.awt.Color(242, 173, 132));
        inventarioBTN.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        inventarioBTN.setForeground(new java.awt.Color(255, 255, 255));
        inventarioBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/truck 48x48.png"))); // NOI18N
        inventarioBTN.setText("Inventario");
        inventarioBTN.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        inventarioBTN.setBorderPainted(false);
        inventarioBTN.setFocusPainted(false);
        inventarioBTN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inventarioBTN.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        inventarioBTN.setIconTextGap(10);
        inventarioBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inventarioBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inventarioBTNMouseExited(evt);
            }
        });
        inventarioBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioBTNActionPerformed(evt);
            }
        });

        ventasBTN.setBackground(new java.awt.Color(242, 173, 132));
        ventasBTN.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        ventasBTN.setForeground(new java.awt.Color(255, 255, 255));
        ventasBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dollar 48x48.png"))); // NOI18N
        ventasBTN.setText("Ventas");
        ventasBTN.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ventasBTN.setBorderPainted(false);
        ventasBTN.setFocusPainted(false);
        ventasBTN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ventasBTN.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ventasBTN.setIconTextGap(10);
        ventasBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ventasBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ventasBTNMouseExited(evt);
            }
        });
        ventasBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasBTNActionPerformed(evt);
            }
        });

        opcionesBTN.setBackground(new java.awt.Color(242, 173, 132));
        opcionesBTN.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        opcionesBTN.setForeground(new java.awt.Color(255, 255, 255));
        opcionesBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/settings 48x48.png"))); // NOI18N
        opcionesBTN.setText("Opciones");
        opcionesBTN.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        opcionesBTN.setBorderPainted(false);
        opcionesBTN.setFocusPainted(false);
        opcionesBTN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        opcionesBTN.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        opcionesBTN.setIconTextGap(10);
        opcionesBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                opcionesBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                opcionesBTNMouseExited(evt);
            }
        });
        opcionesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesBTNActionPerformed(evt);
            }
        });

        reportesBTN.setBackground(new java.awt.Color(242, 173, 132));
        reportesBTN.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        reportesBTN.setForeground(new java.awt.Color(255, 255, 255));
        reportesBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/note 48x48.png"))); // NOI18N
        reportesBTN.setText("Reportes");
        reportesBTN.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        reportesBTN.setBorderPainted(false);
        reportesBTN.setFocusPainted(false);
        reportesBTN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reportesBTN.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        reportesBTN.setIconTextGap(10);
        reportesBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportesBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportesBTNMouseExited(evt);
            }
        });
        reportesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesBTNActionPerformed(evt);
            }
        });

        brandLBL2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        brandLBL2.setForeground(new java.awt.Color(255, 255, 255));
        brandLBL2.setText("Dashboard");

        javax.swing.GroupLayout btnPanelLayout = new javax.swing.GroupLayout(btnPanel);
        btnPanel.setLayout(btnPanelLayout);
        btnPanelLayout.setHorizontalGroup(
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inventarioBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
            .addComponent(ventasBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(opcionesBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(reportesBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btnPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(brandLBL2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnPanelLayout.setVerticalGroup(
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(brandLBL2)
                .addGap(26, 26, 26)
                .addComponent(inventarioBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ventasBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reportesBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionesBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        copyrightLBL.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        copyrightLBL.setText("© 2016 - 2017 Prunus, Chile.");

        innerBodyPanel.setBackground(new java.awt.Color(252, 110, 57));
        innerBodyPanel.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));
        innerBodyPanel.setPreferredSize(new java.awt.Dimension(232, 449));
        innerBodyPanel.setLayout(new java.awt.CardLayout());

        opcionesSubMenuPanel.setBackground(new java.awt.Color(252, 110, 57));

        configurarUsuarioBTN.setBackground(new java.awt.Color(252, 110, 57));
        configurarUsuarioBTN.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        configurarUsuarioBTN.setForeground(new java.awt.Color(255, 255, 255));
        configurarUsuarioBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/key 48x48.png"))); // NOI18N
        configurarUsuarioBTN.setText("Config. Usuario");
        configurarUsuarioBTN.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        configurarUsuarioBTN.setBorderPainted(false);
        configurarUsuarioBTN.setFocusPainted(false);
        configurarUsuarioBTN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        configurarUsuarioBTN.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        configurarUsuarioBTN.setIconTextGap(10);
        configurarUsuarioBTN.setMaximumSize(new java.awt.Dimension(141, 48));
        configurarUsuarioBTN.setMinimumSize(new java.awt.Dimension(141, 48));
        configurarUsuarioBTN.setPreferredSize(new java.awt.Dimension(141, 48));
        configurarUsuarioBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                configurarUsuarioBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                configurarUsuarioBTNMouseExited(evt);
            }
        });

        javax.swing.GroupLayout opcionesSubMenuPanelLayout = new javax.swing.GroupLayout(opcionesSubMenuPanel);
        opcionesSubMenuPanel.setLayout(opcionesSubMenuPanelLayout);
        opcionesSubMenuPanelLayout.setHorizontalGroup(
            opcionesSubMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(configurarUsuarioBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        opcionesSubMenuPanelLayout.setVerticalGroup(
            opcionesSubMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesSubMenuPanelLayout.createSequentialGroup()
                .addComponent(configurarUsuarioBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 387, Short.MAX_VALUE))
        );

        innerBodyPanel.add(opcionesSubMenuPanel, "card2");

        inventarioSubMenuPanel.setBackground(new java.awt.Color(252, 110, 57));

        productosBTN.setBackground(new java.awt.Color(252, 110, 57));
        productosBTN.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        productosBTN.setForeground(new java.awt.Color(255, 255, 255));
        productosBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/shop 48x48.png"))); // NOI18N
        productosBTN.setText("Productos");
        productosBTN.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        productosBTN.setBorderPainted(false);
        productosBTN.setFocusPainted(false);
        productosBTN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        productosBTN.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        productosBTN.setIconTextGap(10);
        productosBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productosBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productosBTNMouseExited(evt);
            }
        });

        categoriasBTN.setBackground(new java.awt.Color(252, 110, 57));
        categoriasBTN.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        categoriasBTN.setForeground(new java.awt.Color(255, 255, 255));
        categoriasBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tag 48x48.png"))); // NOI18N
        categoriasBTN.setText("Categorías");
        categoriasBTN.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        categoriasBTN.setBorderPainted(false);
        categoriasBTN.setFocusPainted(false);
        categoriasBTN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        categoriasBTN.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        categoriasBTN.setIconTextGap(10);
        categoriasBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                categoriasBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                categoriasBTNMouseExited(evt);
            }
        });

        javax.swing.GroupLayout inventarioSubMenuPanelLayout = new javax.swing.GroupLayout(inventarioSubMenuPanel);
        inventarioSubMenuPanel.setLayout(inventarioSubMenuPanelLayout);
        inventarioSubMenuPanelLayout.setHorizontalGroup(
            inventarioSubMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productosBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(categoriasBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        inventarioSubMenuPanelLayout.setVerticalGroup(
            inventarioSubMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventarioSubMenuPanelLayout.createSequentialGroup()
                .addComponent(productosBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(categoriasBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 321, Short.MAX_VALUE))
        );

        innerBodyPanel.add(inventarioSubMenuPanel, "card2");

        ventasSubMenuPanel.setBackground(new java.awt.Color(252, 110, 57));

        detalleVentasBTN.setBackground(new java.awt.Color(252, 110, 57));
        detalleVentasBTN.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        detalleVentasBTN.setForeground(new java.awt.Color(255, 255, 255));
        detalleVentasBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wallet 48x48.png"))); // NOI18N
        detalleVentasBTN.setText("Ventas");
        detalleVentasBTN.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        detalleVentasBTN.setBorderPainted(false);
        detalleVentasBTN.setFocusPainted(false);
        detalleVentasBTN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        detalleVentasBTN.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        detalleVentasBTN.setIconTextGap(10);
        detalleVentasBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                detalleVentasBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                detalleVentasBTNMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ventasSubMenuPanelLayout = new javax.swing.GroupLayout(ventasSubMenuPanel);
        ventasSubMenuPanel.setLayout(ventasSubMenuPanelLayout);
        ventasSubMenuPanelLayout.setHorizontalGroup(
            ventasSubMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detalleVentasBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        ventasSubMenuPanelLayout.setVerticalGroup(
            ventasSubMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventasSubMenuPanelLayout.createSequentialGroup()
                .addComponent(detalleVentasBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 387, Short.MAX_VALUE))
        );

        innerBodyPanel.add(ventasSubMenuPanel, "card2");

        reportesSubMenuPanel.setBackground(new java.awt.Color(252, 110, 57));

        ventasRealizadasBTN.setBackground(new java.awt.Color(252, 110, 57));
        ventasRealizadasBTN.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        ventasRealizadasBTN.setForeground(new java.awt.Color(255, 255, 255));
        ventasRealizadasBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/note 48x48.png"))); // NOI18N
        ventasRealizadasBTN.setText("Ventas Realizadas");
        ventasRealizadasBTN.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ventasRealizadasBTN.setBorderPainted(false);
        ventasRealizadasBTN.setFocusPainted(false);
        ventasRealizadasBTN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ventasRealizadasBTN.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ventasRealizadasBTN.setIconTextGap(10);
        ventasRealizadasBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ventasRealizadasBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ventasRealizadasBTNMouseExited(evt);
            }
        });

        stockProductosBTN.setBackground(new java.awt.Color(252, 110, 57));
        stockProductosBTN.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        stockProductosBTN.setForeground(new java.awt.Color(255, 255, 255));
        stockProductosBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/data 48x48.png"))); // NOI18N
        stockProductosBTN.setText("Stock de Productos");
        stockProductosBTN.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        stockProductosBTN.setBorderPainted(false);
        stockProductosBTN.setFocusPainted(false);
        stockProductosBTN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stockProductosBTN.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        stockProductosBTN.setIconTextGap(10);
        stockProductosBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stockProductosBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stockProductosBTNMouseExited(evt);
            }
        });

        javax.swing.GroupLayout reportesSubMenuPanelLayout = new javax.swing.GroupLayout(reportesSubMenuPanel);
        reportesSubMenuPanel.setLayout(reportesSubMenuPanelLayout);
        reportesSubMenuPanelLayout.setHorizontalGroup(
            reportesSubMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stockProductosBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ventasRealizadasBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        reportesSubMenuPanelLayout.setVerticalGroup(
            reportesSubMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportesSubMenuPanelLayout.createSequentialGroup()
                .addComponent(ventasRealizadasBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(stockProductosBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 321, Short.MAX_VALUE))
        );

        innerBodyPanel.add(reportesSubMenuPanel, "card2");

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addComponent(btnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(copyrightLBL)
                        .addContainerGap())))
            .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bodyPanelLayout.createSequentialGroup()
                    .addGap(161, 161, 161)
                    .addComponent(innerBodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(277, Short.MAX_VALUE)))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(copyrightLBL)
                .addContainerGap())
            .addComponent(btnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                    .addGap(0, 78, Short.MAX_VALUE)
                    .addComponent(innerBodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inventarioBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventarioBTNMouseEntered
        inventarioBTN.setBackground(new Color(255, 153, 102));
    }//GEN-LAST:event_inventarioBTNMouseEntered

    private void inventarioBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventarioBTNMouseExited
        inventarioBTN.setBackground(new Color(242,173,132));
    }//GEN-LAST:event_inventarioBTNMouseExited

    private void ventasBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventasBTNMouseEntered
        ventasBTN.setBackground(new Color(255, 153, 102));
    }//GEN-LAST:event_ventasBTNMouseEntered

    private void ventasBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventasBTNMouseExited
        ventasBTN.setBackground(new Color(242,173,132));
    }//GEN-LAST:event_ventasBTNMouseExited

    private void reportesBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportesBTNMouseEntered
        reportesBTN.setBackground(new Color(255, 153, 102));
    }//GEN-LAST:event_reportesBTNMouseEntered

    private void reportesBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportesBTNMouseExited
        reportesBTN.setBackground(new Color(242,173,132));
    }//GEN-LAST:event_reportesBTNMouseExited

    private void opcionesBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcionesBTNMouseEntered
        opcionesBTN.setBackground(new Color(255, 153, 102));
    }//GEN-LAST:event_opcionesBTNMouseEntered

    private void opcionesBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcionesBTNMouseExited
        opcionesBTN.setBackground(new Color(242,173,132));
    }//GEN-LAST:event_opcionesBTNMouseExited

    private void inventarioBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioBTNActionPerformed
        innerBodyPanel.setVisible(true);
        inventarioSubMenuPanel.setVisible(true);
        ventasSubMenuPanel.setVisible(false);
        reportesSubMenuPanel.setVisible(false);
        opcionesSubMenuPanel.setVisible(false);
    }//GEN-LAST:event_inventarioBTNActionPerformed

    private void ventasBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasBTNActionPerformed
        innerBodyPanel.setVisible(true);
        inventarioSubMenuPanel.setVisible(false);
        ventasSubMenuPanel.setVisible(true);
        reportesSubMenuPanel.setVisible(false);
        opcionesSubMenuPanel.setVisible(false);
    }//GEN-LAST:event_ventasBTNActionPerformed

    private void reportesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesBTNActionPerformed
        innerBodyPanel.setVisible(true);
        inventarioSubMenuPanel.setVisible(false);
        ventasSubMenuPanel.setVisible(false);
        reportesSubMenuPanel.setVisible(true);
        opcionesSubMenuPanel.setVisible(false);
    }//GEN-LAST:event_reportesBTNActionPerformed

    private void opcionesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesBTNActionPerformed
        innerBodyPanel.setVisible(true);
        inventarioSubMenuPanel.setVisible(false);
        ventasSubMenuPanel.setVisible(false);
        reportesSubMenuPanel.setVisible(false);
        opcionesSubMenuPanel.setVisible(true);
    }//GEN-LAST:event_opcionesBTNActionPerformed

    private void bodyPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bodyPanelMouseClicked
        this.cerrarMenu();
    }//GEN-LAST:event_bodyPanelMouseClicked

    private void productosBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productosBTNMouseEntered
        productosBTN.setBackground(new Color(239, 79, 45));
    }//GEN-LAST:event_productosBTNMouseEntered

    private void productosBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productosBTNMouseExited
        productosBTN.setBackground(new Color(252, 110, 57));
    }//GEN-LAST:event_productosBTNMouseExited

    private void categoriasBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriasBTNMouseEntered
        categoriasBTN.setBackground(new Color(239, 79, 45));
    }//GEN-LAST:event_categoriasBTNMouseEntered

    private void categoriasBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriasBTNMouseExited
        categoriasBTN.setBackground(new Color(252, 110, 57));
    }//GEN-LAST:event_categoriasBTNMouseExited

    private void detalleVentasBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detalleVentasBTNMouseEntered
        detalleVentasBTN.setBackground(new Color(239, 79, 45));
    }//GEN-LAST:event_detalleVentasBTNMouseEntered

    private void detalleVentasBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detalleVentasBTNMouseExited
        detalleVentasBTN.setBackground(new Color(252, 110, 57));
    }//GEN-LAST:event_detalleVentasBTNMouseExited

    private void ventasRealizadasBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventasRealizadasBTNMouseEntered
        ventasRealizadasBTN.setBackground(new Color(239, 79, 45));
    }//GEN-LAST:event_ventasRealizadasBTNMouseEntered

    private void ventasRealizadasBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventasRealizadasBTNMouseExited
        ventasRealizadasBTN.setBackground(new Color(252, 110, 57));
    }//GEN-LAST:event_ventasRealizadasBTNMouseExited

    private void stockProductosBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockProductosBTNMouseEntered
        stockProductosBTN.setBackground(new Color(239, 79, 45));
    }//GEN-LAST:event_stockProductosBTNMouseEntered

    private void stockProductosBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockProductosBTNMouseExited
        stockProductosBTN.setBackground(new Color(252, 110, 57));
    }//GEN-LAST:event_stockProductosBTNMouseExited

    private void configurarUsuarioBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configurarUsuarioBTNMouseEntered
        configurarUsuarioBTN.setBackground(new Color(239, 79, 45));
    }//GEN-LAST:event_configurarUsuarioBTNMouseEntered

    private void configurarUsuarioBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configurarUsuarioBTNMouseExited
        configurarUsuarioBTN.setBackground(new Color(252, 110, 57));
    }//GEN-LAST:event_configurarUsuarioBTNMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JLabel brandLBL;
    private javax.swing.JLabel brandLBL2;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton categoriasBTN;
    private javax.swing.JButton configurarUsuarioBTN;
    private javax.swing.JLabel copyrightLBL;
    private javax.swing.JButton detalleVentasBTN;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel innerBodyPanel;
    private javax.swing.JButton inventarioBTN;
    private javax.swing.JPanel inventarioSubMenuPanel;
    private javax.swing.JLabel logoLBL;
    private javax.swing.JButton opcionesBTN;
    private javax.swing.JPanel opcionesSubMenuPanel;
    private javax.swing.JButton productosBTN;
    private javax.swing.JButton reportesBTN;
    private javax.swing.JPanel reportesSubMenuPanel;
    private javax.swing.JButton stockProductosBTN;
    private javax.swing.JButton ventasBTN;
    private javax.swing.JButton ventasRealizadasBTN;
    private javax.swing.JPanel ventasSubMenuPanel;
    private javax.swing.JLabel versionLBL;
    // End of variables declaration//GEN-END:variables
}
