/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.controladorConsultaProducto;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.productoVO;

/**
 *
 * @author Fernando
 */
public class vistaConsultaProducto extends javax.swing.JFrame {
    String codigo="0";
    String codigoselec = "";
    vistaVentas objPantallaVentas = null;
    //vistaVentas objPantallaVentas = null;
    /**
     * Creates new form vistaConsultaProducto
     */
    public vistaConsultaProducto(vistaVentas objPantallaVentas) {
        initComponents();
        URL url = getClass().getResource("/imagenes/logoCarisma.jpg");
        ImageIcon img = new ImageIcon(url);
        setIconImage(img.getImage());
        this.objPantallaVentas = objPantallaVentas;
    }
    public void setControlador(controladorConsultaProducto objControlador){
        volverBTN.addActionListener(objControlador);
        buscarBTN.addActionListener(objControlador);
        
        
        volverBTN.setActionCommand(controladorConsultaProducto.volver);
        buscarBTN.setActionCommand(controladorConsultaProducto.buscar);
    }
    public void despliegaPantalla(){
            setLocationRelativeTo(null);  
            setVisible(true);  
    }    
    public String getfiltro(){
        String filtro = clienteVentaTB.getText();
        return filtro;
    }
    
     public void limpiartexto(){
         clienteVentaTB.setText("");
     }    
     public void llenartabla(ArrayList<productoVO> listaden, int y, int i){
        DefaultTableModel dt =(DefaultTableModel)this.jTable1.getModel();
            dt.addRow(new Object[y]);
            this.jTable1.setValueAt(listaden.get(y).getCodProducto() , y , 0);
            this.jTable1.setValueAt(listaden.get(y).getNomProducto() , y , 1);
            this.jTable1.setValueAt(listaden.get(y).getPrecioProducto() , y , 2);
            this.jTable1.setValueAt(listaden.get(y).getStockProducto() , y, 3) ;
            this.jTable1.setValueAt(listaden.get(y).getMarcaProducto() , y , 4);
            this.jTable1.setValueAt(listaden.get(y).getDescProducto() , y, 5) ;            
    }
    public void limpiartabla(){
        DefaultTableModel dt =(DefaultTableModel)jTable1.getModel();
        dt.setRowCount(0);
    }       
        public void Mensaje(String mensaje){
        JOptionPane.showMessageDialog(null, mensaje);
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        dataSearchLBL = new javax.swing.JLabel();
        volverBTN = new javax.swing.JButton();
        clienteVentaTB = new javax.swing.JTextField();
        buscarBTN = new javax.swing.JButton();
        tipoDocLBL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(202, 18, 30));

        dataSearchLBL.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        dataSearchLBL.setForeground(new java.awt.Color(255, 255, 255));
        dataSearchLBL.setText("Criterios de Búsqueda");

        volverBTN.setBackground(new java.awt.Color(153, 0, 51));
        volverBTN.setForeground(new java.awt.Color(255, 255, 255));
        volverBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Previous_2-64.png"))); // NOI18N
        volverBTN.setContentAreaFilled(false);
        volverBTN.setHideActionText(true);
        volverBTN.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        clienteVentaTB.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        clienteVentaTB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                clienteVentaTBKeyTyped(evt);
            }
        });

        buscarBTN.setBackground(new java.awt.Color(153, 0, 51));
        buscarBTN.setForeground(new java.awt.Color(255, 255, 255));
        buscarBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search-64.png"))); // NOI18N
        buscarBTN.setContentAreaFilled(false);
        buscarBTN.setHideActionText(true);
        buscarBTN.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        tipoDocLBL.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        tipoDocLBL.setForeground(new java.awt.Color(255, 255, 255));
        tipoDocLBL.setText("Ingrese Nombre del Producto");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dataSearchLBL))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clienteVentaTB, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoDocLBL))
                        .addGap(29, 29, 29)
                        .addComponent(buscarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(volverBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscarBTN)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(dataSearchLBL)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(tipoDocLBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clienteVentaTB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(volverBTN)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Precio", "Stock", "Marca", "Descripción"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      if(evt.getClickCount()==2){
        int seleccion = selecciontablanumero();
          capturacodigo(seleccion);
          codigoselec = capturacodigo(seleccion);
          objPantallaVentas.setcodigo(codigoselec);
          //objPantallaVentas.setVisible(true);
          limpiartabla();
          limpiartexto();
          this.dispose();
          
          //objPantallaVentas.setcodigo(capturacodigo(seleccion));
       }        
    }//GEN-LAST:event_jTable1MouseClicked

    private void clienteVentaTBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clienteVentaTBKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }
        if (clienteVentaTB.getText().length() == 30) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_clienteVentaTBKeyTyped
    
    public int selecciontablanumero(){
            int numFilaSeleccionada = this.jTable1.getSelectedRow();  
        return numFilaSeleccionada;            
    } 
    public String capturacodigo(int dato){
        DefaultTableModel dt =(DefaultTableModel)this.jTable1.getModel();
        codigo = jTable1.getModel().getValueAt(dato, 0).toString().trim();
        return codigo;
    }    
    public String getcodigo2(){
        String dato = codigo;
        return dato;
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarBTN;
    private javax.swing.JTextField clienteVentaTB;
    private javax.swing.JLabel dataSearchLBL;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JLabel tipoDocLBL;
    private javax.swing.JButton volverBTN;
    // End of variables declaration//GEN-END:variables
}
