package vista;

import controlador.controladorLogin;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.awt.Color;

public class vistaLogin extends javax.swing.JFrame {

    /**
     * Creates new form vistaLogin
     */
    public vistaLogin() {
        initComponents();
        URL url = getClass().getResource("/imagenes/logoCarisma.jpg");
        ImageIcon img = new ImageIcon(url);
        setIconImage(img.getImage());
        userTB.requestFocus();
    }

    public void setControlador(controladorLogin objControlador){
        loginBTN.addActionListener(objControlador);
        loginBTN.setActionCommand(controladorLogin.botonLogin);
        passTB.addActionListener(objControlador);
        passTB.setActionCommand(controladorLogin.passTextbox);
    }
    
    public String getUsuario(){
        return userTB.getText();
    }
    
    public String getPassword(){
        return passTB.getText();
    }
    
    public void mensaje(String mensaje){
        JOptionPane.showMessageDialog(null, mensaje);
    }
    
    public void despliegaPantalla(){
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        userTB = new javax.swing.JTextField();
        passTB = new javax.swing.JPasswordField();
        loginBTN = new javax.swing.JButton();
        usuarioLBL = new javax.swing.JLabel();
        contraseñaLBL = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        loginLBL = new javax.swing.JLabel();
        organizationPanel = new javax.swing.JPanel();
        organizationBrand = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 51));
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setResizable(false);

        loginPanel.setBackground(new java.awt.Color(36, 46, 66));

        userTB.setBackground(new java.awt.Color(36, 46, 66));
        userTB.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        userTB.setForeground(new java.awt.Color(255, 255, 255));
        userTB.setToolTipText("");
        userTB.setBorder(null);
        userTB.setCaretColor(new java.awt.Color(255, 255, 255));
        userTB.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userTB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userTBKeyTyped(evt);
            }
        });

        passTB.setBackground(new java.awt.Color(36, 46, 66));
        passTB.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        passTB.setForeground(new java.awt.Color(255, 255, 255));
        passTB.setToolTipText("");
        passTB.setBorder(null);
        passTB.setCaretColor(new java.awt.Color(255, 255, 255));
        passTB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passTBKeyTyped(evt);
            }
        });

        loginBTN.setBackground(new java.awt.Color(98, 212, 196));
        loginBTN.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        loginBTN.setText("Iniciar Sesión");
        loginBTN.setBorder(null);
        loginBTN.setBorderPainted(false);
        loginBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBTNMouseExited(evt);
            }
        });

        usuarioLBL.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        usuarioLBL.setForeground(new java.awt.Color(255, 255, 255));
        usuarioLBL.setText("Usuario");

        contraseñaLBL.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        contraseñaLBL.setForeground(new java.awt.Color(255, 255, 255));
        contraseñaLBL.setText("Contraseña");

        loginLBL.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        loginLBL.setForeground(new java.awt.Color(255, 255, 255));
        loginLBL.setText("Login");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                            .addComponent(loginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(58, 58, 58))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passTB, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(contraseñaLBL)
                                .addComponent(usuarioLBL)
                                .addComponent(jSeparator1)
                                .addComponent(userTB))))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(loginLBL)
                        .addGap(85, 85, 85)))
                .addGap(20, 20, 20))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(loginLBL)
                .addGap(18, 18, 18)
                .addComponent(usuarioLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userTB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contraseñaLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passTB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(loginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        organizationPanel.setBackground(new java.awt.Color(202, 18, 30));

        organizationBrand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carismaLogo.jpg"))); // NOI18N

        javax.swing.GroupLayout organizationPanelLayout = new javax.swing.GroupLayout(organizationPanel);
        organizationPanel.setLayout(organizationPanelLayout);
        organizationPanelLayout.setHorizontalGroup(
            organizationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(organizationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(organizationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addGroup(organizationPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(organizationBrand)))
                .addGap(20, 20, 20))
            .addGroup(organizationPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        organizationPanelLayout.setVerticalGroup(
            organizationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(organizationPanelLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(organizationBrand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(organizationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(organizationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userTBKeyTyped
        if (userTB.getText().length() == 15) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_userTBKeyTyped

    private void passTBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passTBKeyTyped
        if (passTB.getText().length() == 10) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_passTBKeyTyped

    private void loginBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBTNMouseEntered
        loginBTN.setBackground(new Color(0, 153, 153));
    }//GEN-LAST:event_loginBTNMouseEntered

    private void loginBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBTNMouseExited
        loginBTN.setBackground(new Color(98, 212, 196));
    }//GEN-LAST:event_loginBTNMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contraseñaLBL;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton loginBTN;
    private javax.swing.JLabel loginLBL;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel organizationBrand;
    private javax.swing.JPanel organizationPanel;
    private javax.swing.JPasswordField passTB;
    private javax.swing.JTextField userTB;
    private javax.swing.JLabel usuarioLBL;
    // End of variables declaration//GEN-END:variables
}
